language: python
python:
  - "3.6"

services:
  - mongodb

install:
  - pip install -r requirements.txt

script:
  - py.test  --cov-report term --cov=app/models --cov=app/controllers --cov=app/exceptions --cov=app/decorators

after_success:
  - codecov
